service: product

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

functions:
  getProductData:
    handler: handler.getProductData
    events:
      - http:
          path: product/data/:id
          method: GET
  saveProductData:
    handler: handler.saveProductData
    events:
      - http:
          path: product/save
          method: POST
